services:
  pd:
    image: pingcap/pd:latest
    ports:
      - "2379:2379"
    volumes:
      - ./data/pd:/data/pd
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
      - --data-dir=/data/pd
    restart: on-failure

  tikv:
    image: pingcap/tikv:latest
    depends_on:
      - pd
    ports:
      - "20160:20160"
    volumes:
      - ./data/tikv:/data/tikv
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --data-dir=/data/tikv
      - --pd=pd:2379
    restart: on-failure

  tidb:
    image: pingcap/tidb:latest
    depends_on:
      - tikv
    ports:
      - "4000:4000"
      - "10080:10080"
    command:
      - --store=tikv
      - --path=pd:2379
      - --advertise-address=tidb
    restart: on-failure