# .air.toml 配置檔案

# 工作目錄
# . 或絕對路徑，請注意以下目錄必須在 root 目錄下
root = "."
tmp_dir = "tmp"

# 通用監聽設置
[build]
# 只需要監聽 .go 文件的變化
include_ext = ["go"]
# 忽略這些檔案
exclude_dir = ["assets", "tmp", "vendor", ".git", "redis_data", "migrations"]
# 默認為 lottery_service，可通過環境變量 AIR_SERVICE 切換
cmd = "go build -o ./tmp/main ./cmd/${AIR_SERVICE:=lottery_service}/main.go"
# 二進位執行文件，必須與 cmd 的編譯輸出一致
bin = "tmp/main"
# 清理檔案
clean_on_exit = true
# 發送中斷信號，重新啟動程序（適用於無法正常關閉的情況）
send_interrupt = true
# 延遲多少秒才重新啟動
delay = 1000 # ms
# 檔案變更時顯示通知
notify = true

# 彩票服務特定配置
[lottery_service]
cmd = "go build -o ./tmp/main ./cmd/lottery_service/main.go"
bin = "tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata", "cmd/host_service"]

# 主持人服務特定配置
[host_service]
cmd = "go build -o ./tmp/main ./cmd/host_service/main.go"
bin = "tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata", "cmd/lottery_service"]

# 日誌設置
[log]
# 顯示日誌時間
time = true

# 顏色設置
[color]
# 自定義各個部分的顏色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

# 其他設置
[misc]
# 在終端中刪除先前的輸出
clean_on_exit = true