version: '3.8'

services:
  # 樂透服務
  lottery-service:
    build:
      context: ../..  # 指向項目的根目錄
      dockerfile: deploy/lottery_service/Dockerfile
    image: lottery-service:latest
    container_name: lottery-service
    restart: unless-stopped
    environment:
      - NACOS_ADDR=http://nacos:8848
      # 保留舊版環境變數以確保向後相容
      - NACOS_HOST=nacos
      - NACOS_PORT=8848
      - NACOS_NAMESPACE=public
      - NACOS_GROUP=DEFAULT_GROUP
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - NACOS_DATAID=lottery-service
      - ENABLE_NACOS=true
    ports:
      - "9100:9100"  # gRPC 服務端口 (從 50051 修改為 9100)
      - "8080:8080"    # WebSocket 端口
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - nacos
      - redis
      - tidb
      - rocketmq-namesrv
      - rocketmq-broker
    networks:
      - lottery-network

  # Nacos 服務
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: unless-stopped
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=18000
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - lottery-network

  # TiDB 服務
  tidb:
    image: pingcap/tidb:latest
    container_name: tidb
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "10080:10080"
    command:
      - --store=mocktikv
      - --path=/tmp/tidb
      - --log-file=/logs/tidb.log
    volumes:
      - tidb-data:/tmp/tidb
      - tidb-logs:/logs
    networks:
      - lottery-network

  # Redis 服務
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass "redis123"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - lottery-network

  # RocketMQ 名稱服務器
  rocketmq-namesrv:
    image: apache/rocketmq:latest
    container_name: rocketmq-namesrv
    restart: unless-stopped
    ports:
      - "9876:9876"
    volumes:
      - rocketmq-namesrv-logs:/home/rocketmq/logs
      - rocketmq-namesrv-store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
      - lottery-network

  # RocketMQ Broker
  rocketmq-broker:
    image: apache/rocketmq:latest
    container_name: rocketmq-broker
    restart: unless-stopped
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - rocketmq-broker-logs:/home/rocketmq/logs
      - rocketmq-broker-store:/home/rocketmq/store
      - ./rocketmq/broker.conf:/opt/rocketmq/conf/broker.conf
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /opt/rocketmq/conf/broker.conf
    depends_on:
      - rocketmq-namesrv
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
    networks:
      - lottery-network

  # RocketMQ Dashboard（管理介面）
  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    restart: unless-stopped
    ports:
      - "8180:8080"  # 修改為 8180 避免與 lottery-service 的 8080 端口衝突
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-namesrv:9876
    depends_on:
      - rocketmq-namesrv
    networks:
      - lottery-network

# 定義網絡
networks:
  lottery-network:
    name: lottery-network
    driver: bridge

# 定義持久化儲存
volumes:
  nacos-data:
  nacos-logs:
  tidb-data:
  tidb-logs:
  redis-data:
  rocketmq-namesrv-logs:
  rocketmq-namesrv-store:
  rocketmq-broker-logs:
  rocketmq-broker-store: 