version: '3.8'

services:
  # PostgreSQL 數據庫
  postgres:
    image: postgres:14-alpine
    container_name: shoppingcart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingcart
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shoppingcart-network

  # Redis 緩存
  redis:
    image: redis:6-alpine
    container_name: shoppingcart-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shoppingcart-network

  # API 網關服務
  api-gateway:
    image: ${DOCKERHUB_USERNAME}/shoppingcart-api-gateway:latest
    container_name: shoppingcart-api-gateway
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Taipei
      - NACOS_HOST=${NACOS_HOST}
      - NACOS_PORT=${NACOS_PORT}
      - NACOS_NAMESPACE=${NACOS_NAMESPACE}
      - NACOS_GROUP=${NACOS_GROUP}
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
      - NACOS_DATAID=api_gateway_config
      - NACOS_SERVICE_NAME=api-gateway
      - ENABLE_NACOS=${ENABLE_NACOS}
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - shoppingcart-network

  # 用戶服務
  user-service:
    image: ${DOCKERHUB_USERNAME}/shoppingcart-user-service:latest
    container_name: shoppingcart-user-service
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Taipei
      - NACOS_HOST=${NACOS_HOST}
      - NACOS_PORT=${NACOS_PORT}
      - NACOS_NAMESPACE=${NACOS_NAMESPACE}
      - NACOS_GROUP=${NACOS_GROUP}
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
      - NACOS_DATAID=user_service_config
      - NACOS_SERVICE_NAME=user-service
      - ENABLE_NACOS=${ENABLE_NACOS}
      - SERVER_PORT=9000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shoppingcart
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - shoppingcart-network

networks:
  shoppingcart-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: